# This is a generated file. Not intended for manual editing.
services:
  movie-knight:
    build:
      context: "C:\\Projects\\Movie-Knight"
      dockerfile: "Movie-Knight/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "/riderDebugger/linux-x64/dotnet/dotnet"
    - "/riderDebugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net7.0/Movie-Knight.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "C:\\Users\\reall\\.nuget\\packages"
      NUGET_FALLBACK_PACKAGES: "C:\\Users\\reall\\.nuget\\packages"
      RIDER_DEBUGGER_LOG_DIR: "/riderLogs"
      RESHARPER_LOG_CONF: "/riderLogsConf/backend-log.xml"
    image: "movie-knight:dev"
    ports:
    - "127.0.0.1:57001:57100"
    - "127.0.0.1:57201:57300"
    volumes:
    - "C:\\Users\\reall\\AppData\\Roaming\\Microsoft\\UserSecrets:/root/.microsoft/usersecrets"
    - "C:\\Users\\reall\\.nuget\\packages:/root/.nuget/fallbackpackages"
    - "C:\\Projects\\Movie-Knight\\Movie-Knight:/app:rw"
    - "C:\\Projects\\Movie-Knight:/src:rw"
    - "C:\\Users\\reall\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2023.2.3\\\
      Linux64:/riderDebugger"
    - "C:\\Users\\reall\\AppData\\Local\\JetBrains\\Installations\\Rider221/bin:/riderLogsConf"
    - "C:\\Users\\reall\\AppData\\Local\\JetBrains\\Rider2023.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2023_11_21_16_41_46:/riderLogs:rw"
    working_dir: "/app"
